// packages/ui-react/src/App.tsx
import { useState } from 'react';
import ChessScene from './components/ChessScene';
import {
    PlayerProfile,
    CapturedPiecesDock,
    MoveHistory,
    GameStatusBanner,
    ThemeSelector,
    ControlsBar,
} from './components/Overlay';
import { useChessEngine } from './hooks/useChessEngine';
import { getThemeById } from './themes';

export default function App() {
    const chess = useChessEngine();
    const [themeId, setThemeId] = useState('marble');
    const theme = getThemeById(themeId);

    return (
        <div className="w-screen h-screen relative overflow-hidden">
            {/* ─── Full-screen 3D Canvas ─────────────────────────── */}
            <div className="absolute inset-0">
                <ChessScene
                    board={chess.board}
                    theme={theme}
                    selectedSquare={chess.selectedSquare}
                    legalMoveSquares={chess.legalMoveSquares}
                    onSquareClick={chess.selectSquare}
                />
            </div>

            {/* ─── UI Overlays (glassmorphism) ───────────────────── */}
            <div className="absolute inset-0 pointer-events-none p-4 flex flex-col">
                {/* ── Top Bar ──────────────────────────────────────── */}
                <div className="flex items-start justify-between gap-4 pointer-events-auto">
                    {/* Logo / Title */}
                    <div className="glass-panel px-5 py-3">
                        <h1 className="text-lg font-bold tracking-tight bg-gradient-to-r from-white to-white/60 bg-clip-text text-transparent">
                            ♔ PolyglotChess
                        </h1>
                        <p className="text-[10px] text-white/40 uppercase tracking-widest mt-0.5">
                            React · Three.js
                        </p>
                    </div>

                    {/* Theme Selector */}
                    <ThemeSelector currentTheme={theme} onThemeChange={setThemeId} />
                </div>

                {/* ── Middle Row ───────────────────────────────────── */}
                <div className="flex-1 flex items-stretch justify-between py-4">
                    {/* Left Column: Players + Captures */}
                    <div className="flex flex-col gap-3 w-52 pointer-events-auto">
                        <PlayerProfile color="b" name="Player 2" isActive={chess.turn === 'b'} />
                        <CapturedPiecesDock captures={chess.capturedPieces} />
                        <div className="flex-1" />
                        <PlayerProfile color="w" name="Player 1" isActive={chess.turn === 'w'} />
                    </div>

                    {/* Center: Game status */}
                    <div className="flex-1 flex items-center justify-center pointer-events-auto">
                        <GameStatusBanner status={chess.gameStatus} />
                    </div>

                    {/* Right Column: Move History */}
                    <div className="w-56 pointer-events-auto">
                        <MoveHistory history={chess.moveHistory} />
                    </div>
                </div>

                {/* ── Bottom Bar ───────────────────────────────────── */}
                <div className="flex items-end justify-between pointer-events-auto">
                    <ControlsBar onUndo={chess.undo} onReset={chess.reset} />
                    <div className="glass-badge text-white/40">
                        FEN: <span className="font-mono text-[10px]">{chess.fen.split(' ').slice(0, 2).join(' ')}…</span>
                    </div>
                </div>
            </div>
        </div>
    );
}

// packages/ui-svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { Canvas } from '@threlte/core';
  import { ChessEngine, type BoardState, type PieceInfo, type MoveInfo, type CapturedPieces, type GameStatus } from '@chess/core';
  import type { Square } from 'chess.js';
  import ChessBoard3D from './components/ChessBoard3D.svelte';
  import Sidebar from './components/Sidebar.svelte';

  const THEMES = [
    { id: 'marble', name: 'Classic Marble', icon: '🏛️', light: '#f0d9b5', dark: '#b58863', wPiece: '#faf5ef', bPiece: '#2c2520', selected: '#7bcc70', legal: '#7bcc70', edge: '#6b4423', bg1: '#1a0f08', bg2: '#0d0805' },
    { id: 'cyberpunk', name: 'Cyberpunk Neon', icon: '🌃', light: '#1a1a2e', dark: '#0f0f1a', wPiece: '#00fff5', bPiece: '#ff00e5', selected: '#ffff00', legal: '#00ff88', edge: '#0a0a14', bg1: '#0a001a', bg2: '#000810' },
    { id: 'glass', name: 'Minimalist Glass', icon: '💎', light: '#e0e0e8', dark: '#9898a8', wPiece: '#ffffff', bPiece: '#2a2a35', selected: '#6366f1', legal: '#818cf8', edge: '#4a4a58', bg1: '#0f0f14', bg2: '#08080c' },
  ];

  let engine = new ChessEngine();
  let board: (PieceInfo | null)[][] = engine.getBoard().board;
  let turn: 'w' | 'b' = 'w';
  let moveHistory: MoveInfo[] = [];
  let captures: CapturedPieces = { white: [], black: [] };
  let gameStatus: GameStatus = engine.getGameStatus();
  let selectedSquare: Square | null = null;
  let legalMoves: Square[] = [];
  let themeIdx = 0;
  $: theme = THEMES[themeIdx];

  const unsubs: (() => void)[] = [];

  onMount(() => {
    unsubs.push(
      engine.events.subscribe('boardUpdate', (s: BoardState) => { board = s.board; turn = s.turn; gameStatus = engine.getGameStatus(); }),
      engine.events.subscribe('moveUpdate', ({ history }) => { moveHistory = [...history]; }),
      engine.events.subscribe('capturesUpdate', (c: CapturedPieces) => { captures = { ...c }; }),
      engine.events.subscribe('reset', () => { moveHistory = []; selectedSquare = null; legalMoves = []; }),
    );
  });

  onDestroy(() => unsubs.forEach(u => u()));

  function selectSquare(sq: Square) {
    if (gameStatus.isGameOver) return;
    if (selectedSquare === sq) { selectedSquare = null; legalMoves = []; return; }
    if (selectedSquare && legalMoves.includes(sq)) {
      engine.move({ from: selectedSquare, to: sq, promotion: 'q' });
      selectedSquare = null; legalMoves = []; return;
    }
    const row = 8 - parseInt(sq[1]);
    const col = sq.charCodeAt(0) - 97;
    const piece = board[row]?.[col];
    if (piece && piece.color === turn) {
      selectedSquare = sq;
      legalMoves = engine.getLegalMoves(sq).map(m => m.to);
    } else { selectedSquare = null; legalMoves = []; }
  }

  function undo() { engine.undo(); selectedSquare = null; legalMoves = []; }
  function reset() { engine.reset(); }
</script>

<div class="w-screen h-screen relative overflow-hidden" style="background: linear-gradient(135deg, {theme.bg1}, {theme.bg2})">
  <!-- 3D Canvas -->
  <div class="absolute inset-0">
    <Canvas>
      <ChessBoard3D {board} {theme} {selectedSquare} {legalMoves} on:squareClick={(e) => selectSquare(e.detail)} />
    </Canvas>
  </div>

  <!-- UI Overlays -->
  <div class="absolute inset-0 pointer-events-none p-4 flex flex-col">
    <!-- Top Bar -->
    <div class="flex items-start justify-between pointer-events-auto">
      <div class="glass-panel px-5 py-3">
        <h1 class="text-lg font-bold bg-gradient-to-r from-white to-white/60 bg-clip-text text-transparent">♔ PolyglotChess</h1>
        <p class="text-[10px] text-white/40 uppercase tracking-widest mt-0.5">Svelte · Threlte</p>
      </div>
      <div class="glass-panel px-3 py-2 flex gap-1.5">
        {#each THEMES as t, i}
          <button class="glass-button text-xs {themeIdx === i ? 'glass-button-active' : ''}" on:click={() => themeIdx = i}>
            {t.icon} <span class="hidden sm:inline">{t.name}</span>
          </button>
        {/each}
      </div>
    </div>

    <!-- Middle -->
    <div class="flex-1 flex items-stretch justify-between py-4">
      <Sidebar {turn} {captures} {gameStatus} side="left" />
      <div class="flex-1" />
      <Sidebar {moveHistory} side="right" />
    </div>

    <!-- Bottom -->
    <div class="flex gap-2 pointer-events-auto">
      <button class="glass-button text-xs" on:click={undo}>↩ Undo</button>
      <button class="glass-button text-xs" on:click={reset}>⟳ New Game</button>
    </div>
  </div>
</div>
